env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - google
parserOptions:
  ecmaVersion: 8
  sourceType: script
overrides:
  -
    files:
      - setup.js
    env:
      browser: false
      node: true
    parserOptions:
      ecmaVersion: 2018
