image: node:15-alpine

stages:
    - lint
    - build
    - deploy

eslint:
    stage: lint
    script:
        - npm i
        - npm test

build:
    stage: build
    script:
        - npm i
        - npm run build
        - find public -type f -regex '.*\.\(css\|html\|js\|json\|svg\)$' -exec gzip -k {} \;
    artifacts:
        paths:
            - public


pages:
    stage: deploy
    script:
        - 'true'
    dependencies:
        - build
    artifacts:
        paths:
            - public
    only:
        - pages
